name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t packtraktest1 . -f test/Dockerfile.1
      - name: Run Docker Tests
        run: docker run packtraktest1
